
name: Build 

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:    
      - name: Initialization Environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - run: go install github.com/damoncoo/gox@master

      - name: Checkout Code
        uses: actions/checkout@master

      - name: Build...
        run: |
          make all
          ls

      - name: Upload Release Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./chatgpt-wecom_*
          tag: 0.15
          file_glob: true
          overwrite: true
          release_name: Auto Release            

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/damoncoo/wecom:latest